"""empty message

Revision ID: ddd3a2f3a145
Revises: 
Create Date: 2019-05-16 13:08:34.585065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddd3a2f3a145'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'technicians', ['phone_number'])
    op.alter_column('testinfo', 'date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('traffic_controllers', sa.Column('enumber', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'traffic_controllers', 'employees', ['enumber'], ['enumber'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'traffic_controllers', type_='foreignkey')
    op.drop_column('traffic_controllers', 'enumber')
    op.alter_column('testinfo', 'date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'technicians', type_='unique')
    # ### end Alembic commands ###
